### ISSUE TITLE
Choose a license!

### ISSUE THREAD

**Issue by mobin-2008** [qasem-talaee/wine-pyqt5#2]
Hello. Unfortunately, it is not clear at this time which license the project uses
This confuses the project participants.
So please select a license for the project

ToDo:

- [x] Choose a license 
- [x] Write a LICENSE file (8efc9798412beec1d2975ff2bacef68f0ba34f8f)

Suggested but not required:
- [ ] Write a summary of the License at the beginning of the source code of the application

**Comment by qasem-talaee** [comment]
Thank you.
