### ISSUE TITLE
Memory Leak ( I guess )

### ISSUE THREAD

**Issue by KeVs404** [qasem-talaee/wine-pyqt5#3]
After trying to add existing prefix (I chose the wine prefix in /home/.wine) the program started maxing out my 16 GB of ram and my system completely hanged, I tested it again to make sure and the same thing happened.

**Comment by qasem-talaee** [comment]
Hello.I did what you did and I did not see anything wrong.Please do two works.
1. Install the wine with its own button
2. If possible, send the terminal output.
Thanks

**Comment by KeVs404** [comment]
[Output.txt](https://github.com/qasem-talaee/wine-pyqt5/files/8734011/Output.txt)

So basically I uninstalled wine from my system, launched your app and pressed install wine. This is the output.

**Comment by qasem-talaee** [comment]
Please remove winehq repository.
[https://askubuntu.com/questions/1118619/unable-to-remove-winehq-from-repositories-used-by-apt-get](https://askubuntu.com/questions/1118619/unable-to-remove-winehq-from-repositories-used-by-apt-get)
Then remove wine.
`sudo apt remove --purge wine*`
and try install again from software.

**Comment by KeVs404** [comment]
i did it now and it gave me the same error  : unable to locate package *dxvk*

**Comment by qasem-talaee** [comment]
Please update source code and try again.

**Comment by KeVs404** [comment]
still the same error, it's okay maybe it's on my side, if it works for everyone else then the problem is not your program so it's okay. Thank you for helping!
